"""Launch, track and stop headless DOSBox-X instances driven through the agent pipe.

Each instance gets its own directory under %LOCALAPPDATA%\\dosbox-llm\\instances\\<id>
holding the agent config, the process log, save states and instance.json, so separate
processes (the MCP server, several `dbx` invocations) can find and share it.
"""
from __future__ import annotations

import ctypes
import json
import os
import shutil
import subprocess
import time
import uuid
from ctypes import wintypes
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from dosbox_agent import AgentClient, AgentError

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_BUILD = REPO_ROOT / "bin" / "x64" / "Agent Release SDL2" / "dosbox-x.exe"

CREATE_NO_WINDOW = 0x08000000
CREATE_NEW_PROCESS_GROUP = 0x00000200
PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
STILL_ACTIVE = 259


class HarnessError(RuntimeError):
    """A harness-level failure with a message meant for the model driving DOSBox-X."""


def state_root() -> Path:
    base = os.environ.get("DOSBOX_LLM_HOME")
    if base:
        return Path(base)
    return Path(os.environ.get("LOCALAPPDATA", Path.home())) / "dosbox-llm"


def default_executable() -> Path:
    configured = os.environ.get("DOSBOX_X_EXE")
    return Path(configured) if configured else DEFAULT_BUILD


@dataclass
class Instance:
    id: str
    pid: int
    endpoint: str
    directory: str
    config_path: str
    exe: str
    mount_dir: str | None
    show: bool
    started_at: float
    session_id: str | None = None
    last_operation_id: str | None = None
    extra: dict[str, Any] = field(default_factory=dict)

    @property
    def path(self) -> Path:
        return Path(self.directory)

    def client(self) -> AgentClient:
        return AgentClient.from_config(self.config_path)

    def alive(self) -> bool:
        return process_alive(self.pid)

    def save(self) -> None:
        (self.path / "instance.json").write_text(json.dumps(asdict(self), indent=2), encoding="utf-8")

    def log_tail(self, lines: int = 30) -> str:
        for name in ("dosbox-x.log", "stdout.log"):
            log = self.path / name
            if log.exists() and log.stat().st_size:
                return "\n".join(log.read_text(encoding="utf-8", errors="replace").splitlines()[-lines:])
        return ""


def process_alive(pid: int) -> bool:
    if os.name != "nt":
        try:
            os.kill(pid, 0)
        except OSError:
            return False
        return True
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    kernel32.OpenProcess.restype = wintypes.HANDLE
    handle = kernel32.OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, False, pid)
    if not handle:
        return False
    try:
        code = wintypes.DWORD()
        if not kernel32.GetExitCodeProcess(handle, ctypes.byref(code)):
            return False
        return code.value == STILL_ACTIVE
    finally:
        kernel32.CloseHandle(handle)


def pipe_exists(endpoint: str) -> bool:
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    kernel32.WaitNamedPipeW.argtypes = [wintypes.LPCWSTR, wintypes.DWORD]
    kernel32.WaitNamedPipeW.restype = wintypes.BOOL
    return bool(kernel32.WaitNamedPipeW(endpoint, 50))


def _write_agent_config(path: Path, endpoint: str, exe: Path, workdir: Path, timeout_ms: int) -> None:
    path.write_text("\n".join([
        "# generated by dosbox_mcp",
        "transport=named_pipe",
        f"endpoint={endpoint}",
        f"dosbox_executable={exe}",
        f"dosbox_workdir={workdir}",
        "profile=production",
        f"request_timeout_ms={timeout_ms}",
        "max_message_bytes=33554432",
        "max_memory_read_bytes=1048576",
        "max_trace_events=10000",
        "raw_debugger_commands=all",
        "",
    ]), encoding="utf-8")


def launch(*,
           mount_dir: str | os.PathLike[str] | None = None,
           program: str | None = None,
           conf: str | os.PathLike[str] | None = None,
           show: bool = False,
           inspector: bool = False,
           cycles: str | None = None,
           extra_args: list[str] | tuple[str, ...] = (),
           exe: str | os.PathLike[str] | None = None,
           startup_timeout_s: float = 60.0,
           request_timeout_ms: int = 15000) -> Instance:
    """Start DOSBox-X headless (or visibly with show=True) and wait until the agent answers."""
    executable = Path(exe) if exe else default_executable()
    if not executable.is_file():
        raise HarnessError(f"DOSBox-X executable not found: {executable} (build it with build.ps1 or set DOSBOX_X_EXE)")
    mount = Path(mount_dir).resolve() if mount_dir else None
    if mount is not None and not mount.is_dir():
        raise HarnessError(f"mount_dir is not a directory: {mount}")

    instance_id = uuid.uuid4().hex[:8]
    directory = state_root() / "instances" / instance_id
    directory.mkdir(parents=True, exist_ok=True)
    endpoint = rf"\\.\pipe\dosbox-llm-{instance_id}"
    config_path = directory / "agent.env"
    _write_agent_config(config_path, endpoint, executable.resolve(), mount or directory, request_timeout_ms)

    args = [str(executable), "--agent-config", str(config_path), "-fastlaunch", "-nopromptfolder"]
    if not show:
        args.append("-headless")
    elif inspector:
        args.append("-inspector")  # palette / video-mode window next to the emulator
    if conf:
        args += ["-conf", str(Path(conf).resolve())]
    else:
        args.append("-defaultconf")
    # Never pause or deprioritise when the (possibly hidden) window lacks focus.
    args += ["-set", "sdl priority=higher,higher"]
    # stdout is rebound to the (hidden) console once the debugger starts, so keep a real log file too.
    args += ["-set", f"log logfile={directory / 'dosbox-x.log'}"]
    if not show:
        args += ["-set", "sdl output=surface"]
    if cycles:
        args += ["-set", f"cpu cycles={cycles}"]
    if mount is not None:
        args += ["-c", f'mount c "{mount}"', "-c", "c:"]
    if program:
        args += ["-c", program]
    args += list(extra_args)

    log = open(directory / "stdout.log", "wb")
    try:
        process = subprocess.Popen(
            args,
            cwd=directory,
            stdin=subprocess.DEVNULL,
            stdout=log,
            stderr=subprocess.STDOUT,
            creationflags=(CREATE_NO_WINDOW | CREATE_NEW_PROCESS_GROUP) if os.name == "nt" else 0,
            close_fds=True,
        )
    finally:
        log.close()

    instance = Instance(
        id=instance_id, pid=process.pid, endpoint=endpoint, directory=str(directory),
        config_path=str(config_path), exe=str(executable), mount_dir=str(mount) if mount else None,
        show=show, started_at=time.time(), extra={"args": args},
    )
    instance.save()

    deadline = time.monotonic() + startup_timeout_s
    while time.monotonic() < deadline:
        if process.poll() is not None:
            raise HarnessError(f"DOSBox-X exited during startup (code {process.returncode}).\n{instance.log_tail()}")
        if pipe_exists(endpoint):
            try:
                # machine.status runs on the emulation thread, so success means the machine is up.
                instance.client().machine_status()
                return instance
            except AgentError:
                pass
        time.sleep(0.2)
    stop(instance, graceful=False)
    raise HarnessError(f"DOSBox-X did not become ready within {startup_timeout_s:.0f}s.\n{instance.log_tail()}")


def list_instances(include_dead: bool = False) -> list[Instance]:
    root = state_root() / "instances"
    if not root.is_dir():
        return []
    found: list[Instance] = []
    for info in root.glob("*/instance.json"):
        try:
            instance = Instance(**json.loads(info.read_text(encoding="utf-8")))
        except (OSError, ValueError, TypeError):
            continue
        if include_dead or instance.alive():
            found.append(instance)
    return sorted(found, key=lambda item: item.started_at)


def get_instance(instance_id: str | None = None) -> Instance:
    """Find a live instance by id (or unique id prefix); with no id, the most recently started one."""
    live = list_instances()
    if not live:
        raise HarnessError("No DOSBox-X instance is running; launch one first")
    if instance_id is None:
        return live[-1]
    matches = [item for item in live if item.id.startswith(instance_id)]
    if len(matches) != 1:
        raise HarnessError(f"No unique running instance matches '{instance_id}'")
    return matches[0]


def stop(instance: Instance, graceful: bool = True, timeout_s: float = 5.0) -> None:
    if graceful and instance.alive():
        try:
            instance.client().trigger_mapper("hand_shutdown")
        except AgentError:
            pass
        deadline = time.monotonic() + timeout_s
        while instance.alive() and time.monotonic() < deadline:
            time.sleep(0.1)
    if instance.alive():
        if os.name == "nt":
            subprocess.run(["taskkill", "/PID", str(instance.pid), "/T", "/F"], capture_output=True, check=False)
        else:
            os.kill(instance.pid, 9)


def prune(keep_logs: bool = False) -> int:
    """Delete directories of instances that are no longer running."""
    removed = 0
    for instance in list_instances(include_dead=True):
        if not instance.alive() and not keep_logs:
            shutil.rmtree(instance.path, ignore_errors=True)
            removed += 1
    return removed
